"""add agenda and workshop_steps

Revision ID: d58fd5206c6f
Revises: 0bede2b1663c
Create Date: 2026-07-12 17:48:06.727647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd58fd5206c6f'
down_revision: Union[str, Sequence[str], None] = '0bede2b1663c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modules', sa.Column('agenda', sa.JSON(), nullable=True))
    op.add_column('modules', sa.Column('workshop_steps', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('modules', 'workshop_steps')
    op.drop_column('modules', 'agenda')
    # ### end Alembic commands ###
