# Application Constants

# User Roles
ROLE_ADMIN = "Admin"
ROLE_EMPLOYEE = "Employee"
ROLES = [ROLE_ADMIN, ROLE_EMPLOYEE]

# Assessment Attempt Status
STATUS_PASS = "pass"
STATUS_FAIL = "fail"
ATTEMPT_STATUSES = [STATUS_PASS, STATUS_FAIL]

# Module Progress Status
PROGRESS_NOT_STARTED = "not_started"
PROGRESS_IN_PROGRESS = "in_progress"
PROGRESS_COMPLETED = "completed"
PROGRESS_STATUSES = [PROGRESS_NOT_STARTED, PROGRESS_IN_PROGRESS, PROGRESS_COMPLETED]

# Question Types
QUESTION_SINGLE = "single_choice"
QUESTION_MULTIPLE = "multiple_choice"
QUESTION_TYPES = [QUESTION_SINGLE, QUESTION_MULTIPLE]

# Difficulty Levels
DIFFICULTY_EASY = "Easy"
DIFFICULTY_MEDIUM = "Medium"
DIFFICULTY_HARD = "Hard"
DIFFICULTY_LEVELS = [DIFFICULTY_EASY, DIFFICULTY_MEDIUM, DIFFICULTY_HARD]

# Resource Types
RESOURCE_PDF = "pdf"
RESOURCE_DWG = "dwg"
RESOURCE_VIDEO = "video"
RESOURCE_LINK = "link"
RESOURCE_TYPES = [RESOURCE_PDF, RESOURCE_DWG, RESOURCE_VIDEO, RESOURCE_LINK]

# Quiz Import Status
IMPORT_PENDING = "pending"
IMPORT_PROCESSING = "processing"
IMPORT_COMPLETED = "completed"
IMPORT_FAILED = "failed"
IMPORT_STATUSES = [IMPORT_PENDING, IMPORT_PROCESSING, IMPORT_COMPLETED, IMPORT_FAILED]
